version: '3.2'

services:

   masterlash:
      container_name: masterlash
      build:
         context: ../
         dockerfile: ./docker/Dockerfile
      image: masterlash
      restart: always
      # ports:
      #    - 3100:3100
